### ISSUE TITLE
Tab crashes in storybook example in Mac

### ISSUE THREAD

**Issue by prabirshrestha** [RibirX/Ribir#558]
When running storybook example and selecting "Tabs" it crashes with the following error.

```
thread 'main' panicked at /Users/user/code/tmp/Ribir/widgets/src/tabs.rs:109:10:
Required child `Pair < TabPane, GenWidget >` not specify
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by wjian23** [comment]
Thanks for your feedback @prabirshrestha. This is definitely a bug and we will fix it as soon as possible in the next version. You can continue to try other examples. Hope you can enjoy ribir and work with us to improve it.
